### ISSUE TITLE
Hide technical informations when sending emails

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#109]
Revealing information when sending emails, especially the user agent used, might be risky.
We can:

- Allow users to use random user agents when sending emails
- Add an option to send each emails with a random user agent. (http://linuxmafia.com/faq/Mail/muas.html)
- Remove certain headers
- etc.

The platform already removes the version number user agent.

**Comment by arodier** [comment]
Actually implemented in the dev branch, will be merged to master soon.

**Comment by progmaticltd** [comment]
The dev branch remove user agent versions, simple but might be enough.

**Comment by arodier** [comment]
This is now implemented by removing the version of the user agent. Removing the user agent completely, or changing its identity could be possible, albeit the user should have control on this.
