### ISSUE TITLE
Postfixadmin

### ISSUE THREAD

**Issue by neuffer** [progmaticltd/homebox#11]
have you given postfixadmin a thought?
It is a great tool to administrate Postfix, available as a package in Debian and it is a very active project.
https://github.com/postfixadmin/postfixadmin
https://sourceforge.net/projects/postfixadmin/
It works great with postgresql.

**Comment by progmaticltd** [comment]
Hello Neuffer,

Thanks for the suggestion. This tool is apparently great to administer Postfix, but it does not respond to any need I have for now. Moreover, all my users are referenced in an LDAP database, I don't see anything in PostfixAdmin that can manage that.

Do you know any stable and simple tool to manage users in an LDAP database, by any chance?

**Comment by neuffer** [comment]
No, I am keeping all my postfix/dovecot (config/user) data in postgresql.
What are you using as database backend for LDAP?
So far I always considered LDAP as far to complex for a server that really only has one or two users logging in on Unix level (more mail users).
