### ISSUE TITLE
Harden the encryption security of the SMTP server

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#110]
Registering the domain to https://www.starttls-everywhere.org/add-domain/ protect against downgrade attacks.
Lets investigate how this can be done

**Comment by sorcer1122** [comment]
I am going to look into this eventually.

Some privacy-conscious email providers offer encrypted email in transit. Do I understand it correctly that in this case port 25 is blocked and only port 465 is open? I understand that unencrypted emails will be rejected but this is the whole idea here.

**Comment by arodier** [comment]
I think this is different, I added this as a memo to check if this is interesting or not.
You can have a look onto this service. It is to prevent your server to "downgrade" the connection requests to an unencrypted connection. I am not sure if a lot of servers are obeying to this or even referring to this service. If this is not interesting, we can close it to "won't fix".
The other option to look are DANE (issue #112) and the new standard MTA-STS (no issue yet, but we should add one).

**Comment by sorcer1122** [comment]
Tried to implement MTA-STS. It is straight-forward, however I am struggling with nginx. I generated a new certificate for mta-sts subdomain but nginx gives me permission denied error when trying to access fullchain.pem. I checked all the permissions and they are exactly the same as other certificates.

**Comment by sorcer1122** [comment]
I have set up MTA-STS, it is not very difficult but now I need to test it. This manual explains how to set it up - https://www.hardenize.com/blog/mta-sts
I am also planning to enable DANE

**Comment by arodier** [comment]
Thanks for the link, I will test this.
DANE support seems more cumbersome, so I will check when I will have the time.

**Comment by arodier** [comment]
Thanks for the link, @sorcer1122, it works like a charm.
I wrote a new role, mta-sts, I will integrate this into the distribution.
No troubles with app-armor
