### ISSUE TITLE
Add DANE support for the mail server

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#112]
DANE is DNS-based Authentication of Named Entities.

It is an Internet security protocol to allow X.509 digital certificates, commonly used for Transport Layer Security (TLS), to be bound to domain names using Domain Name System Security Extensions (DNSSEC).

**Comment by arodier** [comment]
This seems to be a good start: https://www.internetsociety.org/blog/2016/01/lets-encrypt-certificates-for-mail-servers-and-dane-part-1-of-2/
However, it seems more cumbersome than mta-sts

**Comment by fredericmoulins** [comment]
The [Internet.nl toolbox wiki] looks like a good resource for [DANE support]:
- [handling DANE DNS records] ;
- [implementing with Postfix].

[Internet.nl toolbox wiki]: https://github.com/internetstandards/toolbox-wiki
[DANE support]: https://github.com/internetstandards/toolbox-wiki/blob/master/DANE-for-SMTP-how-to.md
[handling DANE DNS records]: https://github.com/internetstandards/toolbox-wiki/blob/master/DANE-for-SMTP-how-to.md#inbound-e-mail-traffic-publishing-dane-dns-records
[implementing with Postfix]: https://github.com/internetstandards/toolbox-wiki/blob/master/DANE-for-SMTP-how-to.md#implementing-dane-for-smtp-on-postfix-inbound--outbound-e-mail-traffic

**Comment by sorcer1122** [comment]
It seems like I have successfully implemented DANE for the mail server.

![dane](https://user-images.githubusercontent.com/15838362/83607272-d06ed280-a572-11ea-8eab-7d358bb3d8cb.png)
It needs further testing in order to write a manual but looks promising.

**Comment by arodier** [comment]
Hello @sorcer1122. Great, if you submit a PR, we can check the code.
I will invite you to the other repositories, this will give you the framework for local testing.

**Comment by sorcer1122** [comment]
My problem is I have never done any collaboration on github, so it will take me a while to write a code and submit a PR. However, the code should not be very long, it seemed to be a simple process.

**Comment by sorcer1122** [comment]
OK I have faced the following issue. One needs to add new DNS record in order for DANE to work - TLSA where one should add SHA-256 hash of the Letsencrypt certificates. Since LE certificates are updated once every 90 days, the hash will change, so it is recommended to add two TLSA records - one for the current certificate and one for the root certificate (roll-over record). I used this one - https://letsencrypt.org/certs/isrgrootx1.pem.txt

Now, my certificates updates and for some reason DANE stopped working until I calculate new hash, amended both TLSA records and re-signed the whole zone (luckily, there is a script for this). Now trying to understand how to automate this process.

**Comment by arodier** [comment]
There are some hooks, in the LetsEncrypt hooks folder, we are using, that you can take as a sample. For instance, since the jabber server requires a bundle with the certificate and the private key into one pem file, this file is created on each renewal, bu a custom script.
Perhaps you can do everything in one bash script, for instance updating the DNS records in the local bind server.
This suppose we are using the internal bind DNS server, of course.

**Comment by progmaticltd** [comment]
I am testing a fix, in the associated branch. I will see how it is behaving on a live system.

**Comment by progmaticltd** [comment]
Result here so far: https://dane.sys4.de/smtp/rodier.me

**Comment by progmaticltd** [comment]
This is now implemented, ping me if you have any question.
