### ISSUE TITLE
Clarify the installation procedure in the documentation

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#146]
Hello,

A bit stupid question - what is the best way to install it? Manual is silent in relation to this.

Do I need to run: 
ansible-playbook access-check.yml
ansible-playbook access-report.yml
and so on to install everything or is there one command to install everything in my defaults.yml and system.yml?

Thanks

**Comment by krimaeus** [comment]
cd into the `install` directory and run this command:
```
ansible-playbook -i ../config/hosts.yml playbooks/main.yml
```

**Comment by arodier** [comment]
Thank you, @krimaeus .
@sorcer1122 , I will update the documentation in the next release, you are right, this should be clearer and explained.

**Comment by sorcer1122** [comment]
Thanks a lot @krimaeus it worked like a charm!
@arodier would be great. I understand this is an advanced project for people familiar with ansible but a small line on how to start it would be great. I am going to close this.

P.S. as promised in the previous issue, I am now testing this on the small production VPS server.

**Comment by arodier** [comment]
Yes, I understand your point to. I am reopening the issue. I am actually updating the documentation, and I will commit it soon. Feel free to take part in the documentation update.
Out of curiosity, it would be interesting to have a page of the supported VPS providers.

**Comment by sorcer1122** [comment]
Thanks, will do. Currently, I am facing with small issue like A records on my domain's DNS table. Once I fix everything, I will share my results here, so VPS documentation can be added.

**Comment by arodier** [comment]
@sorcer1122 , I will advice you to use the internal DNS server, as it is more secure and less trouble. See the dev documentation for details. I should be able to help you for your DNS set up.

**Comment by sorcer1122** [comment]
@arodier Thanks, would be great. However, I try to avoid Google's 8.8.8.8 DNS for privacy reasons.

Do I understand correctly that in order to use internal DNS I need to enable flag 'bind_default: install: true'? And then change 'forward:' flag?

**Comment by sorcer1122** [comment]
OK got to the first error, which I cannot fix:

TASK [dovecot : Create dovecot conf.d configuration files] *********************************************************************************************************************************
failed: [homebox] (item=10-auth.conf) => changed=false 
  file: 10-auth.conf
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''username_chars'''
failed: [homebox] (item=10-master.conf) => changed=false 
  file: 10-master.conf
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''log_access'''
changed: [homebox] => (item=10-mail.conf)
changed: [homebox] => (item=10-logging.conf)
changed: [homebox] => (item=15-lda.conf)
changed: [homebox] => (item=15-mailboxes.conf)
changed: [homebox] => (item=20-managesieve.conf)
changed: [homebox] => (item=20-imap.conf)
changed: [homebox] => (item=20-lmtp.conf)
changed: [homebox] => (item=90-sieve.conf)
changed: [homebox] => (item=90-plugin.conf)
changed: [homebox] => (item=90-quota.conf)

RUNNING HANDLER [dovecot : Restart dovecot] ************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************
homebox                    : ok=339  changed=84   unreachable=0    failed=1   
localhost                  : ok=0    changed=0    unreachable=0    failed=0 

Where can I find this dict object?

**Comment by arodier** [comment]
You do not have to use 8.8.8.8 for the DNS, you can use any one you want. For instance 1.1.1.1 or opendns:

```yaml
bind:
  # Bind is actually in testing phase, feedback welcome
  install: true
  # Default servers to forward queries
  forward:
    - 208.67.222.222
    - 208.67.220.220
...
```

Et voilà.

**Comment by arodier** [comment]
Sorry, I missed your question, perhaps I will set up a mailing list in a few days, depending on my availabilities. Can you open another bug report, please?

**Comment by sorcer1122** [comment]
https://github.com/progmaticltd/homebox/issues/148

**Comment by arodier** [comment]
I have started to clean-up and to reorganise the documentation. It is now in the dev version. I am doing some tests before pushing on master branch.
See it here: https://homebox.readthedocs.io/en/dev/
