### ISSUE TITLE
Hardening nginx security

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#174]
Hello,

A couple of headers should be added to nginx config to make it more secure:

add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options nosniff;
add_header X-XSS_Protection "1; mode=block";
add_header Strict-Transport-Security "max-age=31536000; includeSubdomain; preload";
add_header Content-Security-Policy...
add_header Referrer-Policy 'strict-origin';

It would also be good to add CSP and Feature-Policy as well.
I tried to add those to nginx.conf http { section but it did not work, so had to add security.conf and use include to include those where needed.

**Comment by arodier** [comment]
The continuous integration platform is being built, but not 100% ready yet.
In the mean time, you can use the tests playbook on any cloud or virtual machine (tests/playbooks/main.yml)
All the tests should pass, especially those that relies on nginx (SOGo, roundcube, etc.)

**Comment by fredericmoulins** [comment]
For reference, Mozilla has a guideline for web security:
https://infosec.mozilla.org/guidelines/web_security

The work done in #238 seems to address the main recommendations.
