### ISSUE TITLE
Adding new domain

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#175]
Hello,

It would be nice to be able to quickly add extra domains to the mail server and add/delete users. One way to achieve this is to install iRedmail admin panel - https://bitbucket.org/zhb/iredadmin-ose/src/default/

Non-pro version is free and is enough for this. However, it does require installing UWSGI.

**Comment by arodier** [comment]
This is out of the question.
One domain per server, and no more. If you need two domains, just use two distributions. A VPS is cheap enough to do this. Moreover, there are many open source solutions alternatives that does this. If this is one of your need, I suggest you to use them.
Sorry, it is a no.
