### ISSUE TITLE
Slapd failed to restart in debug mode

### ISSUE THREAD

**Issue by fredericmoulins** [progmaticltd/homebox#202]
Slapd failed to restart with system.debug being true, so when debug options "-d 8 -d 64 -d 2048" are being passed in /etc/default/slapd.

The fail is reported by systemd as a timeout.
```
$ sudo systemctl restart slapd
Job for slapd.service failed because a timeout was exceeded.
See "systemctl status slapd.service" and "journalctl -xe" for details.
```
There is no specific output in journalctl.
```
août 10 12:12:55 systemd[1]: Starting LSB: OpenLDAP standalone server (Lightweight Directory Access Protocol)...
-- Subject: Unit slapd.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit slapd.service has begun starting up.
août 10 12:12:55 slapd[6269]: @(#) $OpenLDAP: slapd  (May 23 2018 04:25:19) $
                                       Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
août 10 12:13:11 slapd[6269]: slapd starting
août 10 12:17:32 slapd[6269]: connection_input: conn=1005 deferring operation: binding
août 10 12:17:55 systemd[1]: slapd.service: Start operation timed out. Terminating.
août 10 12:17:55 slapd[6262]: Starting OpenLDAP: slapd
août 10 12:17:55 systemd[1]: Failed to start LSB: OpenLDAP standalone server (Lightweight Directory Access Protocol).
-- Subject: Unit slapd.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit slapd.service has failed.
-- 
-- The result is failed.
août 10 12:17:55 systemd[1]: slapd.service: Unit entered failed state.
août 10 12:17:55 systemd[1]: slapd.service: Failed with result 'timeout'.
```
And the slapd process is still hanging there afterwards.
```
$ ps waux | grep slapd
openldap  6269  0.0  0.4 1668008 9832 ?        Sl   12:12   0:00 /usr/sbin/slapd -h ldap://127.0.0.1:389/ ldaps:/// ldapi:/// -g openldap -u openldap -F /etc/ldap/slapd.d -d 8
```

The same behaviour happened with any one of these debug flags set. It starts without issue when no debug flags are passed.

The test server is a vm and not very powerfull, but I am not sure if this is the issue. I have not taken much time to look into it beyond these tests, and have disabled slapd debug for my tests.

Any idea what could cause this, what to check?

**Comment by arodier** [comment]
I did not try the server in debug mode for a while, perhaps I should.
Maybe the debug mode consumes a lot of memory?
I usually recommend 512M for the smallest configurations, and 2G for the biggest ones.
Also, system-prepare normally installs a swap file package (dphys-swapfile IIRC)

**Comment by arodier** [comment]
Same error on a VPS with 1G of ram. I am trying a few things, and I will come back to you.

**Comment by fredericmoulins** [comment]
Ok, thanks.

I think you can also get this commit to the dev branch.
