### ISSUE TITLE
external-ip-check user for cron job

### ISSUE THREAD

**Issue by fredericmoulins** [progmaticltd/homebox#203]
I think the external-ip-check cron job should not be run as root. It makes network requests to untrusted servers, some of which using http, via the `external-ip` script and `wget`.

As it is, it writes to the `/etc/homebox/external-ip` file, so requires root. Maybe this file should be in something like `/var/cache/external-ip/` or `/var/cache/homebox/` with rights associated to a restricted user.

Should there be an apparmor profile for these scripts? (That's easy to ask for :sweat_smile:)

Any thoughts?

**Comment by arodier** [comment]
This seems a good idea.
I would opt for /var/cache/external-ip, but this have implications on other roles as well, so it need to be tested carefully.
External IP address detection seems more complicated than I thought too, especially if the IP address has changed, the DNS records probably need to be updated and the DNS server restarted.
I am happy to receive pull requests ;-)

**Comment by arodier** [comment]
I remove the cron job, as this is the best solution IMHO. I may remove dynamic IP address detection later, or at least design it differently.

**Comment by arodier** [comment]
Removed completely in dev. No automatic detection any more.
