### ISSUE TITLE
Gandi DNS auto update script - update to be able to utilise Gandi v5

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#337]
This is a very helpful feature but https://v4.gandi.net/login is being phased out and will probably stop working this year. Also, all new users are registering with v5 and therefore are not able to use Gandi DNS auto update script since v4 and v5 logins are not interchangeable.

Would be very useful if anyone can update this script to be able to update DNS records via v5.

**Comment by arodier** [comment]
Hello Sorcer,
HomeBox comes with its own DNS server, supporting DNSSEC, and for practical reasons during the deployment, it is better than the Gandi DNS. Therefore, this will be not implemented.
However, there might be something to implement, which will be ZSK and KSK updates on the DNS, whatever it is Gandi or not. There are libraries to access multiple DNS providers API, so this is probably something we want to use on the long term.
Please, close this ticket, and open a second one, more generic, for DNS ZSK and KSK updates. In this case, I will accept it with pleasure.

**Comment by sorcer1122** [comment]
Sure, closing this down, even though I think it would be a nice ### option
