### ISSUE TITLE
Ensure the version of SOGo is working on Buster

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#340]
Currently, homebox is shipped with SOGO ver 3.2.6 I think, which is outdated and deprecated. Current version is 4.3.2 but you will need to buy a (expensive) subscription from SOGO to download a compiled package.
However, it is possible to compile SOGO from source code for free. I wonder if installing ver 4 on top of 3 will mess something up. Any ideas?

**Comment by arodier** [comment]
The version on Buster is the one we'll use. However, even this version is sort-of obsolete, with a a lot of bugs, among one I have reported.

I already sent an email to the Debian mailing list and the maintainers. I have not received any answer from the maintainers, but feel free to send an email too.

https://packages.debian.org/buster/sogo

Overall, the version in Buster is not usable.

If you have some time, you can also help the Debian maintainers to packages the next version. Taking part to this would be fair, IMHO.

**Comment by sorcer1122** [comment]
I would like to try a simpler way - to add SOGO's nightly repositories into sources.list and see whether this will install the latest SOGO directly from inverse's rep instead of using Debian's rep. I guess in this case SOGO will be updated regularly. Will try it in the virtual machine.

I tried to compile the source code, it kind of worked but nothing happened after make install, so clearly there is a problem somewhere.

**Comment by arodier** [comment]
There is no way we will support SOGo nightly build :laughing:...
However, if you fancy help Debian maintainers to publish the version 4.3 earlier, this would be wonderful.
If you want more up to date packages, perhaps use another solution, like those mentioned in the documentation, [Other projects to mention](https://homebox.readthedocs.io/en/latest/#other-projects-to-mention). :smile:

**Comment by arodier** [comment]
I am going to use switch to Bullseye version, as the platform will not be ready before bullseyes.
There is also another issue on Bullseye: https://sogo.nu/bugs/view.php?id=5221

**Comment by arodier** [comment]
I am focusing on developing the bullseye version, which has been updated to 5.0. All bugs of 4.3 are not present any more, which is a very good news!
