### ISSUE TITLE
Roundcube does not work out of the box on Buster

### ISSUE THREAD

**Issue by khushman1** [progmaticltd/homebox#345]
Installed a fresh version with Roundcube, sogo, and other defaults, and Roundcube doesn't work out of the box.
The MTA/SMTP servers work, as I can send and receive email from Thunderbird, but roundcube consistently gives me a HTTP 500 error. I've been trying to debug this issue, and from what I can tell, it is configured to use mysql, but the scripts don't install a version of the server. Will see if manually installing the server helps and report back.

Updates:
1. Needed to install php-mysql package to get past the HTTP 500 errors. Now roundcube doesn't login, and I'm trying to fix that.
2. Needed to create a roundcube database, user, and password from `/etc/dbconfig-common/roundcube.conf` and run the mysql initalization script from `/usr/share/roundcube/SQL/`

**Comment by arodier** [comment]
Thanks for your feedback, I was aware of the issue.
The default installation of RoundCube on Debian Stretch seemed to create the database, so I was expecting an update from buster to do the same. I may use an SQLite too, which should be enough for a family.
I am considering using only one solution, for instance SOGo, so I did not pass too much time on this.

**Comment by arodier** [comment]
Roundcube may not work on Buster, but I am actually working directly with Bullseye, so we should have something on this release directly.

**Comment by arodier** [comment]
I think I am going to remove RoundCube from HomeBox, I am happy with SOGo so far.

**Comment by khushman1** [comment]
I've implemented nextcloud with my homebox and use that for mail, which works out to be a pretty good email/online office solution. Thanks for the updates!

**Comment by arodier** [comment]
I am always a little bit reluctant about PHP and its security holes...
Does NextCloud are finally offering a Debian repository ?
