### ISSUE TITLE
Clarify system.yml filename

### ISSUE THREAD

**Issue by besendorf** [progmaticltd/homebox#348]
As mentioned in #347 the path of `system-example.yml` is wrong in the documentation. However I also noticed that the documentation asks to name the file `system.yml' but the file itself says to copy it to common.yml. Which one is it? Is it even important?
Could you please clarify this?

**Comment by arodier** [comment]
I think the common.yml is an old artefact of the initial code.

**Comment by arodier** [comment]
I cannot find `common.yml` any more in the code, please, tell me where this is referenced and reopen the issue if needed.

**Comment by besendorf** [comment]
It is reference in this exact line:
https://github.com/progmaticltd/homebox/blob/dev/preseed/config/system-example.yml#L9

**Comment by arodier** [comment]
Thanks, I looked into the master branch. I will remove the line

**Comment by arodier** [comment]
This has been fixed in the last PR too.
