### ISSUE TITLE
Failed task: remote-access : Get the external IP address (IPv6)

### ISSUE THREAD

**Issue by markshep** [progmaticltd/homebox#353]
I get a failure on this task because my Ansible controller machine's internet connection is IPv4 only.  This is the output:

````
fatal: [homebox]: FAILED! => changed=false 
  content: ''
  elapsed: 0
  msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 8] nodename nor servname provided, or not known>'
  redirected: false
  status: -1
  url: https://api6.ipify.org/
````

The task is defined in ````install/playbooks/roles/remote-access/tasks/ufw-rules.yml```` and the comment above it says that it's safe to run as it'll return an IPv4 address if there's no IPv6 address.  However I think the behaviour must have changed because it's now failing.

**Comment by arodier** [comment]
Yes, this has been fixed in https://github.com/progmaticltd/homebox/pull/350. I am adding you as a reviewer.

**Comment by senorsmile** [comment]
I had the same issue.  I tested the changes to ufw-public-access.yml and confirmed they work for me.

**Comment by arodier** [comment]
This has been fixed in the commit above. Please re-open if it is not the case
