### ISSUE TITLE
sender_bcc_maps not working

### ISSUE THREAD

**Issue by nestijko** [progmaticltd/homebox#358]
Hello there, I have a problem with my sender_bcc_maps and I don't know what to look for anymore and I hope that someone will help me with it here.

In my main.cf file I have this line :
`sender_bcc_maps = hash:/etc/postfix/sender_bcc`

my sender_bcc file looks like this : 
`...`
`root@domain.com    archiv@domain.com`
`spravca@domain.com archiv@domain.com`
`....`

there are more mail accounts there but this should work too.
I have a mail alias for archiv like this : 
`archiv: zal_odch_posty2`

So if the configuration would work every send mail that is configured in sender_bcc file should be saved in zal_odch_posty2, but I'm unable to get the mails there and I don't know why.

Can anyone help me ? 
Thank you so much.

**Comment by arodier** [comment]
Have you run postmap /etc/postfix/sender_bcc before restarting postfix ?

**Comment by arodier** [comment]
No news, I think this was just a missing postmap command.
