### ISSUE TITLE
Use xapian for dovecot fts

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#359]
Starting with Debian buster, dovecot supports xapian indexing engine for full text search.
I think it is more up to date and more secure than using solr inside a java engine.

- https://packages.debian.org/bullseye/dovecot-fts-xapian
- https://github.com/grosjo/fts-xapian

**Comment by arodier** [comment]
For the attachments, we have to wait for this bug to be fixed: https://github.com/grosjo/fts-xapian/issues/68
Otherwise, the backend seems to work fine.

**Comment by grosjo** [comment]
@arodier Supposedly, latest version fixed the case

**Comment by arodier** [comment]
I can tell the version in Bullseye does not, from the logs:

> `doveadm(camille): Info: FTS Xapian: New part (Header=(null),Type=text/csv,Disposition=attachment; filename="file.csv")`
> `doveadm(camille): Info: FTS Xapian: Skipping part of type 'text/csv' and disposition 'attachment; filename="file.csv"'`
> `doveadm(camille): Info: FTS Xapian: fts_backend_xapian_update_set_mailbox`
> `doveadm(camille): Info: FTS Xapian: Unset box 'INBOX' (c0d4e304584e5460dae30000075d7e67)`

**Comment by arodier** [comment]
Bug report filled on Debian Bullseye: https://bugs.debian.org/985654

**Comment by arodier** [comment]
Fixed in the bullseye branch.

**Comment by progmaticltd** [comment]
Implemented
