### ISSUE TITLE
Postfix Compatibility 3.6 ?

### ISSUE THREAD

**Issue by boddedo** [progmaticltd/homebox#368]
Hello, I have a question,

in Debian 12, the default postfix configuration use "compatibility_level = 3.6"
can we make the change ? do we need to improve the security level somewhere ?
I saw an option about DNSSEC runtime detection in 3.5.9, is it useful to implement that ?

Regards.

**Comment by progmaticltd** [comment]
Homebox comes with its own main.cf configuratin file, so there is nothing to do.

This isn't clear to me. Is there any error with the current implementation ? I am not encouraging compatibility with old version of the SMTP protocol.

By the way, for questions, better email the mailing list, please.

DNSSEC is another topic, so it would deserve another email or issue, if it is one.
