### ISSUE TITLE
grafana api key is saved as grafana/admin with password store

### ISSUE THREAD

**Issue by stelb** [progmaticltd/homebox#376]
Hi,

I am not using passwordstore, but standard password.[^1]

The playbook fails

> grafana : Get the datasource info using the API fails with
> ..
>     message: Invalid API key
> ..
> 

Trying to do it manually fails also with api-key in backup/domain/grafana/api-key

I found following lines, where the api-key is persisted:
https://github.com/progmaticltd/homebox/blob/e51906321019aa617263d55fef9ebf8fb0be2e5c/roles/grafana/tasks/install/config.yml#L96-L114

passwordstore uses ../grafana/api-key while password uses ../grafana/admin

[^1] there is no prompt asking for my gpg password when running with hide_secrets true so it fails, and setting to false helps to continue until it's set to true(hu?) and it fails again. I gave up on this right now.

**Comment by progmaticltd** [comment]
Thanks for spotting the bug, and thanks for the PR
