### ISSUE TITLE
OpenDMARC daemon exits

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#39]
The DMARC daemon, opendmarc exits withoout reason, and does not restart.
I cannot find anything in the filesystem logs, neither any information on journalctl.
It looks like the daemon has been stopped.

**Comment by arodier** [comment]
This has now been fixed in the commit 488b857bb82e8e8ad9fbc17fc24d3d7ff9321b46.

**Comment by progmaticltd** [comment]
This is happening again, opendmarc stops and need to be restarted manually.

**Comment by arodier** [comment]
Now fixed with the last opendmarc package from Debian,
