### ISSUE TITLE
Add syncthing

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#60]
A synchronisation package in Debian repository:
> Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized. Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet

https://syncthing.net/

**Comment by arodier** [comment]
There will be one front end for all the users, with a path prefix as the UID.
nginx will be used as a reverse proxy, with a [systemd](https://github.com/syncthing/syncthing/blob/master/etc/linux-systemd/user/syncthing.service) service.

**Comment by arodier** [comment]
One folder per user will be configured using the examples in the [reverse proxy documentation](https://docs.syncthing.net/users/reverseproxy.html).

**Comment by progmaticltd** [comment]
Not to implement in the core, might be a plugin later.
