### ISSUE TITLE
Disable SOGO feature that copy sent emails in the sent folder

### ISSUE THREAD

**Issue by progmaticltd** [progmaticltd/homebox#69]
SOGo copies sent messages in the sent folder, but this is already done by the mail server.

To avoid this, there might be a flag in SOGo 3 that I am not aware of, or the other option is to delete the message from SOGo in the sent folder.

1. Configure postfix to remove user the agent when messages are sent
2. Delete messages in the sent folder that contains the mail user agent

**Comment by progmaticltd** [comment]
This is fixed in the dev branch, in the commit #106, using sieve scripts in the IMAP Sent folder, in response to the APPEND event. This need to be tested with email imports, though.

**Comment by arodier** [comment]
Now implemented. The sent folder option in SOGo is in fact a "copy to sent" folder
