### ISSUE TITLE
Continuous integration for the deployment scripts

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#76]
Write continuous integration scripts and reports to check on every master commit.
Use Jenkins and the currently hosted scripts to check each installation playbooks.

**Comment by arodier** [comment]
Use Jenkins and the currently hosted scripts to check each installation playbooks.

**Comment by progmaticltd** [comment]
The process is working and tested on Vultr cloud instances by Jenkins, but cannot be published yet. See #180.

**Comment by progmaticltd** [comment]
The Jenkins server is now publicly visible: https://jenkins.homebox.space/.
Documentation will be updated.
