### ISSUE TITLE
Continuous Integration for all the features

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#77]
Write continuous integration scripts and reports to check all the features on every master commit:

- Email: smtp, imap, full text search, etc.
- Collaboration: carddav, caldav, etc.
- Proxying with tor and privoxy
- Gogs repository
- Transmission
- etc.

**Comment by arodier** [comment]
GitLab version 10 available on Debian Stretch backports.
Add Ansible Vultr commands to spawn virtual machines and start a full deployment.

**Comment by progmaticltd** [comment]
Most of the features are tested by Jenkins, but cannot be published yet. See #180.

**Comment by progmaticltd** [comment]
Jenkins is now configured with public access.
