### ISSUE TITLE
Add mail list service

### ISSUE THREAD

**Issue by amedranogil** [progmaticltd/homebox#87]
Add optional/core feature for providing mail listing services, like [Mailman](http://list.org/), I personally prefer [Sympa](https://www.sympa.org/), which can also be linked to LDAP groups dynamically creating mail lists from LDAP groups.

**Comment by arodier** [comment]
Hello Alejandro,
Sorry for the late answer, I missed this!
Yes, this is a feature that can be provided, I was not aware of this requirement, but this is something simple.

**Comment by amedranogil** [comment]
I an't no ansemble conoseur, but here is something that might be useful:
https://github.com/sympa-community/sympa-ansible

**Comment by arodier** [comment]
Thanks, I will have a look.
I will add it soon, I need to create a community mailing list any way.

**Comment by arodier** [comment]
I am lacking time to implement this, and I want to focus on family needs first, so I will postpone this for a while.
However, in thought adding a "modules" folder in the repository, excluded from git, will help third parties to implement modules but have access to all the configuration and other roles.
I will add this when I come back from holidays, but this is already in my branch (dev-arodier).

**Comment by arodier** [comment]
We are not going to implement this, this is not a priority, please, send a PR if you are interested.
