### ISSUE TITLE
Sogo binaries are requesting to read the root filesystem

### ISSUE THREAD

**Issue by progmaticltd** [progmaticltd/homebox#96]
Two tools are opening the root folder ("/") thousand times a day, just for reading and getting the attributes.

This is visible with AppArmor:

    operation="getattr" profile="/usr/sbin/sogo-ealarms-notify" name="/" comm="sogo-ealarms-no" requested_mask="r" fsuid=126 ouid=0
    operation="getattr" profile="/usr/sbin/sogo-tool" name="/" comm="sogo-tool" requested_mask="r" fsuid=126 ouid=0
    operation="open" profile="/usr/sbin/sogo-tool" name="/" comm="sogo-tool" requested_mask="r" fsuid=126 ouid=0

I really wonder why those binaries are opening the root ("/") folder, even for reading and getting the attributes.

- What is the point of doing this?
- Is this a bug?
- Is this fixed in the version 4?

The bug is referenced here: https://sogo.nu/bugs/view.php?id=4704

**Comment by progmaticltd** [comment]
fixed in dev

**Comment by progmaticltd** [comment]
fixed in the dev branch

**Comment by arodier** [comment]
I have removed the audit, and authorised the reading only of '/'. Let's see if this is fixed in SOGo 4.
