### ISSUE TITLE
integrate ansible-lint in the distribution

### ISSUE THREAD

**Issue by progmaticltd** [progmaticltd/homebox#97]
Debian comes with ansible-lint package, this would be nice to integrate it.

**Comment by arodier** [comment]
I am actually blocked by an error when trying to run ansible-lint:

```sh
andre@arthur:Projects/homebox ‹dev*›$ ansible-lint install/playbooks/main.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 11, in <module>
    load_entry_point('ansible-lint==4.1.0+dfsg.1', 'console_scripts', 'ansible-lint')()
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 282, in run
    skip_list=self.skip_list))
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 174, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 84, in matchtasks
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/usr/lib/python2.7/dist-packages/ansiblelint/utils.py", line 603, in append_skipped_rules
    yaml = ruamel.yaml.YAML()
AttributeError: 'module' object has no attribute 'YAML'
```

**Comment by dangarthwaite** [comment]
After `pip3 install -U ansible ansible-lint` I'm able to run `ansible-lint install/playbooks/main.yml` just fine.
I do get screenfulls and screenfulls of warnings.  :)

**Comment by arodier** [comment]
Right. Perhaps some of them can be easily fixed, as long as it does not break the CI/CD in Jenkins.

**Comment by dangarthwaite** [comment]
None of them looked unfixable.
I'm found this issue looking for things to do for #hacktoberfest.  How do I move forward with a PR?  
The project documents says only install tools with `apt-get`.  I installed a newer ansible-lint with `pip install -u`.   After resolving that -- how to integrate it into the project in the form of a PR?  I suggest https://pre-commit.com/ configured to run flake8 and ansible-lint at commit time.  

The advantage of pre-commit is that it will only flag files a developer is currently changing.  It allows for incremental compliance.

**Comment by progmaticltd** [comment]
Hello, Dan.

There might be subtle differences, when the ansible-lint tool will be added
to Jenkins. Try to see if the differences are minor, then go ahead with the
latest version.

Thanks for your help!

André

**Comment by arodier** [comment]
OK, I have started to work on this one...

**Comment by arodier** [comment]
The work done will be integrated in the dev branch soon. This is not perfect, but it is now a good position to improve.

I have (for now) disabled four warnings / errors that can be either fixed later, or kept commented, according to our later choice:

- 701     No 'galaxy_info' found
- 503     Tasks that run when changed should likely be handlers
- 305     Use shell only when shell functionality is required
- 301     Commands should not change things if nothing needs doing

However, it is raising common errors and already highlighted some errors in our tests, which I have fixed.

**Comment by arodier** [comment]
Implemented so far, and works.
